name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: paymongo_example_test 
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.x
          elixir-version: 1.10.x
      - run: mix local.hex --force
      - run: mix local.rebar --force        
      # - run: mix do deps.get, compile --warnings-as-errors
      - run: mix ecto.setup 
      - run: mix credo --strict 
      - run: mix test

